imgix/sf-commerce-cloud

.github/workflows/commitlint.yml

chore: add commitlint GH action

---

frontend/package.json
frontend/src/components/AssetBrowser/AssetBrowser.tsx
frontend/src/components/AssetBrowser/AssetGridContainer.tsx
frontend/src/components/buttons/dropdowns/SourceSelect.tsx
frontend/src/components/grids/AssetGrid.tsx
frontend/src/stories/AssetBrowser.stories.tsx
frontend/src/stories/AssetBrowser.tsx
frontend/src/stories/SourceSelect.stories.tsx
frontend/src/stories/SourceSelect.tsx
frontend/src/styles/AssetBrowser.css
frontend/src/styles/Form.css
frontend/src/styles/SourceSelect.css
frontend/src/types/asset.ts
frontend/src/types/imgixAPITypes.ts
frontend/src/types/index.ts
frontend/src/types/source.ts
frontend/yarn.lock

This commit addresses an issue where the search form would render above the fetched sources dropdown list.
|#27|[PE-1331-1] style: ensure dropdown doesn't cause layout shift - DRAFT|**N/A**|
|#28|[PE-1331-1] chore: shorten placeholder text for search - DRAFT|#27|
|#31|[PE-1331-1] style: set source select z index above search - DRAFT|#28|
|#32|[PE-1331-1] feat: add handleSelect callback to SourceSelect component - DRAFT|#31|
|#33|[PE-1331-1] refactor: use reactimgix to render assets - DRAFT|#32|
|#34|[PE-1331-1] feat: create asset browser component - DRAFT|#33|
|#40|[PE-1331-1] chore: remove duplicate types|#34|
|#41|[PE-1331-1] chore: use imgix api type in components|#40|
|#29|~~[PE-1331-1] chore: add custom domains to source …

[PE-1331-1] style: set source select z index above search

---

cartridges/bm_imgix_pd/cartridge/experience/editors/imgix/imageSelection.js
cartridges/bm_imgix_pd/cartridge/experience/editors/imgix/imageSelection.json
cartridges/bm_imgix_pd/cartridge/static/default/experience/editors/imgix/imageSelection.js
cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.json

|#38|[PE-1485-3] remove unused files from bm cartridge|**N/A**|
|#39|[PE-1485-3] configure custom attribute editor to display iframe|#38|
---
This PR is a large step towards a working sidebar custom attribute editor. This PR will render the following in the sidebar:

[PE-1485-3] configure custom attribute editor to display iframe

---

cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js
cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.json

This PR builds the template logic to handle default params. @syedbadshah-toptal line 16 can be replaced here with the settings that are set in the site settings for this to work.
|#76|feat: implement responsive images and set ixlib|Pending|-|
|#77|👉 chore: write template logic to handle default params|Pending|#76|
|#82|feat: add imgix parameters to component sidebar|Pending|#77|
|#79|Added apikey to defaultParams|Pending|#77|
|#83|feat: correctly set imgix parameters on rendered image|Pending|#82|

[fred] chore: write template logic to handle default params

---

cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js
cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.json
frontend/src/stories/AssetBrowser.stories.tsx
frontend/src/stories/AssetBrowser.tsx

chore: add handleBrowserClick action to AssetBrowser story

---

frontend/src/components/SidebarApp.module.css
frontend/src/components/SidebarApp.tsx
frontend/src/components/buttons/AddImageIcon.tsx
frontend/src/tests/sidebarApp/sidebar_App.test.tsx

This PR begins the work on the styling of the sidebar app to bring it more in line with the intended designs.
|#93|feat: store current custom attribute value and display img|**Approved**|-|
|#94|chore: create story (inc. empty state) for SidebarApp|**Approved**|#93|
|#95|👉 chore: add image wrapper styles and update breakout button|Pending|#94|

[f-3] chore: add image wrapper styles and update breakout button

---

frontend/src/components/SidebarApp.module.css
frontend/src/components/SidebarApp.tsx
frontend/src/components/buttons/AddImageIcon.tsx
frontend/src/stories/SidebarApp.module.css
frontend/src/stories/SidebarApp.stories.tsx
frontend/src/stories/SidebarApp.tsx
frontend/src/tests/sidebarApp/sidebar_App.test.tsx

|#93|feat: store current custom attribute value and display img|**Approved**|-|
|#94|👉 chore: create story (inc. empty state) for SidebarApp|**Approved**|#93|
|#95|chore: add image wrapper styles and update breakout button|Pending|#94|

[f-3] chore: create story (inc. empty state) for SidebarApp

---

frontend/src/components/SidebarApp.module.css
frontend/src/components/SidebarApp.tsx
frontend/src/components/buttons/AddImageIcon.tsx
frontend/src/index-breakout.tsx
frontend/src/index-sidebar.tsx
frontend/src/stories/SidebarApp.module.css
frontend/src/stories/SidebarApp.stories.tsx
frontend/src/stories/SidebarApp.tsx
frontend/src/tests/sidebarApp/sidebar_App.test.tsx
frontend/src/types/imgixSF.ts

This PR stores the return value from the breakout modal and passes it down to the sidebar app. This creates a full working e2e flow 👏 
https://user-images.githubusercontent.com/615334/142011773-71928b37-9ca1-4dc5-a4fc-f67f1bf0d899.mov
|#93|👉 feat: store current custom attribute value and display img|**Approved**|-|
|#94|chore: create story (inc. empty state) for SidebarApp|**Approved**|#93|
|#95|chore: add image wrapper styles and update breakout button|Pending|#94|

[f-3] feat: store current custom attribute value and display img

---

frontend/src/components/AssetBrowser/AssetBrowser.tsx
frontend/src/components/AssetBrowser/AssetBrowserContainer.tsx

This PR addresses [this PR feedback](https://github.com/imgix/sf-commerce-cloud/pull/90#discussion_r750462517)

chore: refactor asset click handling to AssetBrowser [f-5]

---

frontend/src/components/buttons/Button.module.scss
frontend/src/components/buttons/Button.tsx
frontend/src/components/buttons/dropdowns/SourceSelect.module.scss
frontend/src/components/buttons/dropdowns/SourceSelect.tsx
frontend/src/stories/ButtonLayout.css

|#112|feat: add hover state for remove image icon |![](https://img.shields.io/github/pulls/detail/state/imgix/sf-commerce-cloud/112?label=Approved)|-|
|#113|chore: remove AddImageIcon and associated styles |![](https://img.shields.io/github/pulls/detail/state/imgix/sf-commerce-cloud/113?label=Approved)|#112|
|#114|feat: add Spinner component |![](https://img.shields.io/github/pulls/detail/state/imgix/sf-commerce-cloud/114?label=Approved)|#113|
|#115|chore: use new Spinner in AssetGrid component |![](https://img.shields.io/github/pulls/detail/state/imgix/sf-commerce-cloud/115?label=Approved)|#114|
|#116|chore: remove unused LoadingSpinner component |![](https://img.shields.io/github/pulls/detail/state/imgix/sf-c …

chore: rewrite source select css into modular css [f-6]

---

.gh-stack.env
.github/workflows/annotate.yml

build: add gh-stack annotate gh-action

---

frontend/src/common/hooks/useListSelectionBehavior.tsx
frontend/src/components/buttons/Button.module.scss
frontend/src/components/buttons/Button.tsx
frontend/src/components/forms/search/SearchBar.module.scss
frontend/src/components/forms/search/SearchBar.tsx
frontend/src/components/forms/search/useFocus.tsx
frontend/src/components/icons/DisabledSvg.tsx

TSIA
|#129|chore: update source select dropdown, and api calls |**Approved**|#128|
|#131|chore: fix layout and styles of source select and search bar |**Approved**|#129|
|#132|👉 chore: have search-bar take up container width |**Approved**|#131|
|#133|chore(search): refactor on-focus styling |**Approved**|#132|
|#135|chore(search): add buttons to expander …

chore: have search-bar take up container width [f-7]

---

frontend/src/common/hooks/useListSelectionBehavior.tsx
frontend/src/components/AssetBrowser/AssetBrowser.tsx
frontend/src/components/buttons/Button.module.scss
frontend/src/components/buttons/Button.tsx
frontend/src/components/buttons/dropdowns/SourceSelect.module.scss
frontend/src/components/buttons/dropdowns/SourceSelect.tsx
frontend/src/components/forms/search/SearchBar.module.scss
frontend/src/components/forms/search/SearchBar.tsx
frontend/src/components/forms/search/useFocus.tsx
frontend/src/components/icons/DisabledSvg.tsx
frontend/src/components/icons/SourceMenuSvg.module.scss
frontend/src/services/imgixAPIService.ts
frontend/src/stories/Button.stories.tsx
frontend/src/stories/SourceSelect.stories.tsx
frontend/src/types/imgixAPITypes.ts

This PR fixes the sizing of the left icon in the source select dropdown
|#128|👉 chore: fix left icon  |**Approved**|#127|
|#129|~~chore: update source select dropdown, and api calls ~~|**Merged**|#128|
|#131|~~chore: fix layout and styles of source select and search bar ~~|**Merged**|#129|
|#132|~~chore: have search-bar take up container width ~~|**Merged**|#131|
|#133|~~chore(search): refactor on-focus styling …

chore: fix left icon  [f-7]

---

package.json

build: add storybook and deploy scripts

---

frontend/src/components/App.module.scss
frontend/src/components/AssetBrowser/AssetBrowser.module.scss
frontend/src/components/BreakoutApp.tsx
frontend/src/components/grids/AssetGrid.module.scss
frontend/src/components/grids/AssetGrid.tsx
frontend/src/stories/AssetBrowser.stories.tsx

chore: make AssetBrowser and grid take up whole height of container

---

cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js
frontend/src/components/AssetBrowser/AssetBrowser.tsx
frontend/src/components/AssetBrowser/AssetBrowserContainer.tsx
frontend/src/components/forms/search/SearchBar.tsx
frontend/src/components/forms/search/useLocalStorage.tsx
frontend/src/components/grids/AssetGrid.tsx
frontend/src/services/imgixAPIService.ts
frontend/src/tests/breakoutApp/breakout_App.test.tsx

chore: remove todo code comments

---

README.md

TSIA
|#156|👉 docs: remove in development warning|![](https://img.shields.io/github/pulls/detail/state/imgix/sf-commerce-cloud/156?label=Approved)|-|
|#157|docs: remove in active development section|![](https://img.shields.io/github/pulls/detail/state/imgix/sf-commerce-cloud/157?label=Approved)|#156|

docs: remove in development warning [l-1]

---

README.md

TSIA
|#156|docs: remove in development warning|![](https://img.shields.io/github/pulls/detail/state/imgix/sf-commerce-cloud/156?label=Approved)|-|
|#157|👉 docs: remove in active development section|![](https://img.shields.io/github/pulls/detail/state/imgix/sf-commerce-cloud/157?label=Approved)|#156|

docs: remove in active development section [l-1]

---

cartridges/int_imgix_products_sfra/cartridge/models/product/productAttributes.js
cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js
metadata/system-objecttype-extensions.xml
test/unit/int_imgix_products_sfra/models/product/productAttributes.js
test/unit/int_imgix_products_sfra/models/product/productImages.js

This PR has the same content as #150, except it has been rebased on top of the latest changes from `next`
---
product custom attribute implementation completed.
system objects file added in meta data.
unit test added.

feat: add imgix product custom attribute

---

frontend/src/index-extension.tsx

This PR adds a simple scaffold/boilerplate to ensure that upstack PRs can build successfully. The work here will be further developed later (in #180).

chore: add scaffold extension index script

---

frontend/src/index-extension.module.scss
frontend/src/index-extension.tsx
frontend/src/index.tsx
frontend/src/stories/extension/products.stories.tsx
src/extension/manifest.json

This PR implements the content script fully. It uses an interval to ensure that the target element is found reliably, and stops after 30s. Also it now replaces the whole imgix section so the React app can use the whole available space.

feat: implement content script

---

test/unit/int_imgix_products_sfra/models/product/productAttributes.js

Just a small PR fixing some test typos to remove confusion from upstack PRs

test: fix some typos

---

frontend/src/components/InfoPanel/InfoPanel.module.scss
frontend/src/components/InfoPanel/InfoPanel.tsx
frontend/src/stories/extension/InfoPanel.stories.tsx
frontend/src/stories/styles/Grid.stories.tsx

https://user-images.githubusercontent.com/16711614/150616294-980ee060-a34c-4b92-9ea0-44db11d7f62f.mov

feat: create info panel

---

cartridges/SFTypes.js
cartridges/commonTypes.js
cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js

This PR checks in the built files from the TS project. In the future we will probably move everything over to TS, and then will only need to do this during a build step before pushing on the trunk branches.

chore: check in built cartridges files

---

.circleci/config.yml
cartridges/SFTypes.js
cartridges/commonTypes.js
cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js
src/cartridges/commonTypes.ts
src/cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.ts
test/unit/int_imgix_products_sfra/models/product/productImages.js

This PR makes CircleCI build the new cartridges TS project on CI, before running unit tests

chore(ci): build project before testing

---

.circleci/config.yml
cartridges/SFTypes.js
cartridges/commonTypes.js
cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js
src/cartridges/commonTypes.ts
src/cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.ts
test/unit/int_imgix_products_sfra/models/product/productImages.js

Before this PR, CircleCI would build the frontend project 3 times. This doesn't happen anymore.

chore: don't need to build 3 times on CI

---

frontend/src/components/card/AssetCard.tsx
frontend/src/stories/styles/Grid.stories.tsx

chore: update on-click type

---

frontend/src/index-extension.tsx

This commit reads the imgix api key from the `browser.storage`. Once that key has been retrieved, it passes the key on the ExtensionApp. If the browser does not support that API, then it renders the extension without the key as a fallback.

feat(extension): pass storage api key to im modal

---

frontend/src/components/ExtensionApp.tsx
frontend/src/components/layouts/Portal.tsx

This PR prevents the portal background from scrolling when the portal is open.

fix: prevent background scroll when portal open

---

frontend/src/components/ExtensionApp.tsx
frontend/src/components/layouts/Modal.module.scss
frontend/src/components/layouts/Portal.tsx

The IM modal wouldn't open in the right position.
The modal takes account of the SFCC top toolbar when settings its position.

fix: have modal positioning account for toolbar

---

frontend/src/components/ExtensionApp.tsx
frontend/src/components/layouts/Modal.module.scss
frontend/src/components/layouts/Portal.tsx
frontend/src/stories/extension/products.module.scss
frontend/src/stories/extension/products.stories.tsx

refactor: make story styles match sfcc better

---

frontend/src/components/ExtensionApp.module.scss
frontend/src/components/ExtensionApp.tsx
frontend/src/components/buttons/FrameButton/FrameButton.module.scss
frontend/src/components/buttons/dropdowns/SourceSelect.module.scss
frontend/src/components/forms/search/SearchBar.module.scss
frontend/src/components/layouts/Modal.module.scss
frontend/src/components/layouts/Portal.tsx
frontend/src/stories/extension/products.module.scss
frontend/src/stories/extension/products.stories.tsx

SFCC has their products page `rem` set to something other than 16px. This PR explicitly sets the font-size for the application to be `16px`.

fix: ensure font-size is consisntent

---

frontend/src/components/ExtensionApp.module.scss
frontend/src/components/ExtensionApp.tsx
frontend/src/components/buttons/FrameButton/FrameButton.module.scss
frontend/src/components/buttons/dropdowns/SourceSelect.module.scss
frontend/src/components/forms/search/SearchBar.module.scss
frontend/src/components/layouts/Modal.module.scss
frontend/src/components/layouts/Portal.tsx
frontend/src/stories/extension/products.module.scss
frontend/src/stories/extension/products.stories.tsx

This PR adds the `ActionBar` to the `ExtensionApp` and has it save the selection and close the modal on save or cancel.

feat: use action bar to save selection

---

frontend/src/components/ActionBar/ActionBar.module.scss
frontend/src/components/ActionBar/ActionBar.tsx
frontend/src/components/ExtensionApp.module.scss
frontend/src/components/ExtensionApp.tsx
frontend/src/components/buttons/FrameButton/FrameButton.module.scss
frontend/src/components/buttons/dropdowns/SourceSelect.module.scss
frontend/src/components/forms/search/SearchBar.module.scss
frontend/src/components/layouts/Modal.module.scss
frontend/src/components/layouts/Portal.tsx
frontend/src/stories/extension/products.module.scss
frontend/src/stories/extension/products.stories.tsx

This PR creates the ActionBar component. This component will be used by the AssetGrid modal to cancel or submit actions taken inside the modal.

feat: create action bar for extension

---

frontend/src/components/ActionBar/ActionBar.module.scss
frontend/src/components/ActionBar/ActionBar.tsx
frontend/src/components/ExtensionApp.module.scss
frontend/src/components/ExtensionApp.tsx
frontend/src/components/ProductImage/ProductImageContainer.module.scss
frontend/src/components/ProductImage/ProductImageContainer.tsx
frontend/src/components/ProductPageImages.module.scss
frontend/src/components/buttons/FrameButton/FrameButton.module.scss
frontend/src/components/buttons/dropdowns/SourceSelect.module.scss
frontend/src/components/card/AssetCard.module.scss
frontend/src/components/forms/search/SearchBar.module.scss
frontend/src/components/layouts/Modal.module.scss
frontend/src/components/layouts/Portal.tsx
frontend/src/stories/extension/products.module.scss
frontend/src/stories/extension/products.stories.tsx

"sizes" buttons and styling were present in the `ProductImageContainer.tsx`
The sizes buttons and styling are removed.

chore: remove sizes buttons

---

frontend/src/components/ActionBar/ActionBar.module.scss
frontend/src/components/ActionBar/ActionBar.tsx
frontend/src/components/ExtensionApp.module.scss
frontend/src/components/ExtensionApp.tsx
frontend/src/components/ProductImage/ProductImageContainer.module.scss
frontend/src/components/ProductImage/ProductImageContainer.tsx
frontend/src/components/ProductPageImages.module.scss
frontend/src/components/buttons/FrameButton/FrameButton.module.scss
frontend/src/components/buttons/dropdowns/SourceSelect.module.scss
frontend/src/components/card/AssetCard.module.scss
frontend/src/components/forms/search/SearchBar.module.scss
frontend/src/components/layouts/Modal.module.scss
frontend/src/components/layouts/Portal.tsx
frontend/src/index-extension.tsx
frontend/src/stories/extension/products.module.scss
frontend/src/stories/extension/products.stories.tsx

The entire application would crash if the custom_attribute field was empty
If the `custom_attribute.value` field is undefined, we explicitly set it to a string that can be parsed into JSON.

fix: ensure custom attr always has valid json

---

frontend/src/components/ActionBar/ActionBar.module.scss
frontend/src/components/ActionBar/ActionBar.tsx
frontend/src/components/ExtensionApp.module.scss
frontend/src/components/ExtensionApp.tsx
frontend/src/components/ProductImage/ProductImageContainer.module.scss
frontend/src/components/ProductImage/ProductImageContainer.tsx
frontend/src/components/ProductPageImages.module.scss
frontend/src/components/buttons/FrameButton/FrameButton.module.scss
frontend/src/components/buttons/dropdowns/SourceSelect.module.scss
frontend/src/components/card/AssetCard.module.scss
frontend/src/components/forms/search/SearchBar.module.scss
frontend/src/components/layouts/Modal.module.scss
frontend/src/components/layouts/Portal.tsx
frontend/src/index-extension.tsx
frontend/src/stories/extension/products.module.scss
frontend/src/stories/extension/products.stories.tsx

Selected assets were not added to the imgix custom attribute field JSON.
Selected assets are added to the imgix custom attribute field JSON after clicking on "add image".
[add-json-on-click.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/vkhjmXjzdqOiU0HS7RdK/bd2560d2-276d-49c0-91ad-46b84f41e794/add-json-on-click.mov)

feat: save asset to product images on click save

---

frontend/src/components/ActionBar/ActionBar.module.scss
frontend/src/components/ActionBar/ActionBar.tsx
frontend/src/components/ExtensionApp.module.scss
frontend/src/components/ExtensionApp.tsx
frontend/src/components/ProductImage/ProductImageContainer.module.scss
frontend/src/components/ProductImage/ProductImageContainer.tsx
frontend/src/components/ProductPageImages.module.scss
frontend/src/components/ProductPageImages.tsx
frontend/src/components/buttons/FrameButton/FrameButton.module.scss
frontend/src/components/buttons/dropdowns/SourceSelect.module.scss
frontend/src/components/card/AssetCard.module.scss
frontend/src/components/forms/search/SearchBar.module.scss
frontend/src/components/layouts/Modal.module.scss
frontend/src/components/layouts/Portal.tsx
frontend/src/index-extension.tsx
frontend/src/stories/extension/products.module.scss
frontend/src/stories/extension/products.stories.tsx
frontend/src/types/breakoutAppPublic.ts

This PR creates the `IBreakoutAppData` and adds `imgix_metadata` to key to it. This key will be used by a later commit.

feat: add imgix-metadata to breakout-app-data

---

frontend/src/components/ActionBar/ActionBar.module.scss
frontend/src/components/ActionBar/ActionBar.tsx
frontend/src/components/AssetBrowser/AssetBrowser.tsx
frontend/src/components/ExtensionApp.module.scss
frontend/src/components/ExtensionApp.tsx
frontend/src/components/ProductImage/ProductImageContainer.module.scss
frontend/src/components/ProductImage/ProductImageContainer.tsx
frontend/src/components/ProductPageImages.module.scss
frontend/src/components/ProductPageImages.tsx
frontend/src/components/buttons/FrameButton/FrameButton.module.scss
frontend/src/components/buttons/dropdowns/SourceSelect.module.scss
frontend/src/components/card/AssetCard.module.scss
frontend/src/components/forms/search/SearchBar.module.scss
frontend/src/components/layouts/Modal.module.scss
frontend/src/components/layouts/Portal.tsx
frontend/src/index-extension.tsx
frontend/src/stories/extension/products.module.scss
frontend/src/stories/extension/products.stories.tsx
frontend/src/types/breakoutAppPublic.ts

feat: add imgix-metdata to returned object

---

frontend/package.json
frontend/src/stories/extension/products.stories.tsx
frontend/src/tests/extensionApp/extension_App.test.tsx

This PR sets ups the suite for testing the extension component.

test: add test suite for extension component

---

cartridges/int_imgix_products_sfra/cartridge/scripts/imgix/jsCore.js
package.json
src/cartridges/int_imgix_products_sfra/cartridge/scripts/imgix/imgix.ts
yarn.lock

This will give consumers of the products integration cartridge access to the js-core library to help them further modify their images.
Example usage in a custom component:
with isml as:
```
```
Results in:

feat: add imgix sdk script

---

frontend/src/components/buttons/ReplaceButton.tsx
frontend/src/components/layouts/Portal.tsx
frontend/src/stories/extension/products.stories.tsx
frontend/src/tests/extensionApp/extension_App.test.tsx

This PR adds several test cases for extension UI functionality. It also fixes a bug where the extension was being injected twice into the tests.

test: add exension UI tests

---

frontend/src/components/AssetBrowser/AssetBrowserContainer.tsx

This commit adds an optional prop that allows for the asset brwoser to
load a specific source by default.

feat: add optional default-source-id prop

---

frontend/src/components/ExtensionApp.tsx

This PR parses the source ID from the selected image and passes that ID onto the AssetBrowser.

feat: parse selected-ource-id from selected image

---

frontend/src/components/icons/MetaSvg.tsx

This PR creates the `MetaSvg` component. This is an icon that will be used in a subsequent component.

feat: create meta-svg component

---

package.json

chore: add script to watch build changes

---

package.json

chore: add script to bundle extension

---

src/cartridges/tsconfig.json

fix: typescript code version target was incompatible with SF backend

---

frontend/src/components/card/AssetCard.module.scss
frontend/src/components/forms/attributes/AttributeForm.module.scss
frontend/src/components/forms/attributes/AttributeForm.tsx

chore: improve attribute form styling

---

frontend/src/components/AssetBrowser/AssetBrowser.tsx
frontend/src/components/AssetBrowser/AssetBrowserContainer.tsx
frontend/src/components/buttons/dropdowns/SourceSelect.tsx
frontend/src/services/imgixAPIService.ts
frontend/src/stories/SourceSelect.tsx

SourceSelect dropdown would only display a maximum of 20 sources.
More sources can be displayed by clicking a button at the bottom of the list.
https://user-images.githubusercontent.com/16711614/155642096-fc5dbbfb-ebc2-47b5-9e7c-564a7cc5711d.mov

feat: request more sources on click

---

src/extension/options.css
src/extension/options.html
src/extension/options.js

- added styling
- added message after successful save
- allowed empty API key to be saved so that API key can be deleted
FYI in the demo below, the validation logic was slightly changed so that "valid" was a valid key when saving, so I didn't have to expose an actual key when recording this video.
https://user-images.githubusercontent.com/615334/156173396-53883d1c-b254-42b1-b98e-cb12fa77183d.mov

feat: update extension options

---

src/cartridges/tsconfig.json

chore(ts): disable incremental builds

---

cartridges/int_imgix_products_sfra/cartridge/models/product/productAttributes.js

fix: don't break when no custom swatch images are available

---

cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js
src/cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.ts
src/extension/manifest.json

chore(release): extension v1.0.3

---

README.md
package.json
src/extension/options.js

Updating Image Manager language to Asset Manager

Change Image Manage to Asset Manager

---

frontend/package.json
frontend/yarn.lock

chore(deps): upgrade imgix-management-js

---

src/extension/manifest.json

Release new version of chrome extension

chore(release): 1.0.4
