cartridges/app_imgix_base_sfra/cartridge/experience/components/imgix/testcomp.js, cartridges/app_imgix_base_sfra/cartridge/experience/components/imgix/testcomp.json
The priovus commit tried to address this issue by committing the
incorrect spelling. It turns out the issue stemmed from the ID being
uppercased in the json, not the incorrect spelling.
Both the issue with the uppercased ID and the spelling of `ttitle` are
addressed in this commit.
=> fix: actually fix title id spelling

frontend/src/index.tsx
This PR replaces the index script of the CRA app with SF-related code. Some work will probably need to be done to make this "polymorphic" for both apps. I'm not too worried about this though - for now, we can just hard-code this for the sidebar app. This PR is the only PR in this stack ready to merge 😅 
|#42|[PE-1502] chore: add temporary image placeholder - DRAFT|**N/A**|
|#44|[PE-1502] chore: disable create react app chunking - DRAFT|#42|
|#45|[PE-1502] chore: update sidebar app to not break build and load image from imgix|#44|
|#46|[PE-1502] chore: build in SF scripts into frontend build|#45|
|#47|[PE-1502] chore: check in example built working app|#46|
=> [PE-1502] chore: build in SF scripts into frontend build

frontend/.storybook/preview.js, frontend/src/components/AssetBrowser/AssetBrowser.tsx, frontend/src/components/grids/AssetGrid.tsx, frontend/src/services/imgixAPIService.ts, frontend/src/styles/AssetBrowser.css, frontend/src/styles/Grid.css
This PR changes `AssetGrid` styling so that more assets are displayed per page by default. It also changes the `storybook` styling so that the pages have no padding.
https://user-images.githubusercontent.com/16711614/139305499-6ec03793-ff34-4609-b9a3-abb30c1df42f.mov
https://user-images.githubusercontent.com/16711614/139305516-f3cf9257-5eec-476a-9ad4-e8cb83ee3e3c.mov
|#49|[PE-389-1][PE-1531] feat: add loading state to asset grid|**N/A**|
|#51|[PE-389-1][PE-1517] chore: remove the domain prop|#49|
|#52|[PE-389-1][PE-1527] feat: add search to asset browser|#51|
|#53|[PE-389-1][PE-1528] feat: catch and display imgixAPI errors|#52|
|#54|[PE-389-1][PE-1526] feat: add pagination|#53|
|#55|[PE-389-1][PE-1526-1] chore: update grid …
=> [PE-389-1][PE-1526-1] chore: update grid style to show more assets

frontend/.storybook/preview.js, frontend/src/components/AssetBrowser/AssetBrowser.tsx, frontend/src/components/AssetBrowser/AssetBrowserContainer.tsx, frontend/src/components/buttons/Pagination.tsx, frontend/src/components/forms/search/SearchBar.tsx, frontend/src/components/grids/AssetGrid.tsx, frontend/src/services/imgixAPIService.ts, frontend/src/stories/AssetBrowser.tsx, frontend/src/stories/AssetGrid.tsx, frontend/src/styles/AssetBrowser.css, frontend/src/styles/Grid.css, frontend/src/styles/Pagination.css, frontend/src/types/cursor.ts, frontend/src/types/index.ts
This PR adds pagination to the `AssetBrowser` component.
Prior to this PR, each component tried to manage its own slice of the state. This was meant to reducer interdependencies and unnecessary re-renders.
The `AssetBrowserContainer.tsx` component was made into a Class component. This allowed us to move most of the state that needed to be shared by siblings to the parent component. The individual slices of state, and state-setters, that each component needed could then be shared with the siblings as props.
The `requestAssetsFromSource` function and its helpers now accept an object rather than multiple arguments. This made it easier to account for times when, for example, `query` was technically an "optional" parameter but still had to have some sort of value, IE `undefined`, set to it. It …
=> [PE-389-1][PE-1526] feat: add pagination

frontend/.storybook/preview.js, frontend/src/components/AssetBrowser/AssetBrowser.tsx, frontend/src/components/AssetBrowser/AssetBrowserContainer.tsx, frontend/src/components/buttons/Pagination.tsx, frontend/src/components/forms/search/SearchBar.tsx, frontend/src/components/grids/AssetGrid.tsx, frontend/src/services/imgixAPIService.ts, frontend/src/stories/AssetBrowser.tsx, frontend/src/stories/AssetGrid.stories.tsx, frontend/src/stories/AssetGrid.tsx, frontend/src/styles/AssetBrowser.css, frontend/src/styles/Grid.css, frontend/src/styles/LoadingSpinner.css, frontend/src/styles/Pagination.css, frontend/src/types/cursor.ts, frontend/src/types/index.ts
This PR adds a `placeholder` prop to the `AssetGrid` component. 
It also adds an `errors` state to the `AssetBrowser` component. The `imgixAPI` error messages are passed to the `placeholder` prop when they occur to more easily inform the user of any API errors.
The PR also moves the loading spinner inside the grid. This makes it easier to pass the spinner as the `placeholder` prop whenever the `loading` state is `true`.
> Note: the end of the video is where I enter an invalid key
https://user-images.githubusercontent.com/16711614/138493447-cb5b866a-317b-4e59-85c4-eff0af10e5a8.mov
|#49|[PE-389-1][PE-1531] feat: add loading state to asset grid|**N/A**|
|#51|[PE-389-1][PE-1517] chore: remove the domain prop|#49| …
=> [PE-389-1][PE-1528] feat: catch and display imgixAPI errors

frontend/.storybook/preview.js, frontend/src/components/AssetBrowser/AssetBrowser.tsx, frontend/src/components/AssetBrowser/AssetBrowserContainer.tsx, frontend/src/components/buttons/Pagination.tsx, frontend/src/components/forms/search/SearchBar.tsx, frontend/src/components/grids/AssetGrid.tsx, frontend/src/services/imgixAPIService.ts, frontend/src/stories/AssetBrowser.tsx, frontend/src/stories/AssetGrid.stories.tsx, frontend/src/stories/AssetGrid.tsx, frontend/src/stories/SearchBar.tsx, frontend/src/styles/AssetBrowser.css, frontend/src/styles/Form.css, frontend/src/styles/Grid.css, frontend/src/styles/LoadingSpinner.css, frontend/src/styles/Pagination.css, frontend/src/types/cursor.ts, frontend/src/types/index.ts
This PR introduces 3 major changes into the code base in order to enable search:
- This PR creates the `imgixApi.search` method that allows the search bar component to search for assets. This is a placeholder endpoint, as in a future commit this should get refactored to be cleaner and less error-prone. Ideally, we'd actually hit a `/search` endpoint rather than use the same value for tags, filename, etc to filter.
- This PR adds `onSubmit` and `onChange` handlers to the `SearchBar` component. This is necessary in order to change this form into a controlled form. Moreover, it makes integration of this component with custom handlers easier.
- This PR adds search capabilities to the asset browser. The PR includes an `onSearchSubmit` handler that should probably be refactored out of the …
=> [PE-389-1][PE-1527] feat: add search to asset browser

frontend/.storybook/preview.js, frontend/src/components/AssetBrowser/AssetBrowser.tsx, frontend/src/components/AssetBrowser/AssetBrowserContainer.tsx, frontend/src/components/buttons/Pagination.tsx, frontend/src/components/forms/search/SearchBar.tsx, frontend/src/components/grids/AssetGrid.tsx, frontend/src/services/imgixAPIService.ts, frontend/src/stories/AssetBrowser.tsx, frontend/src/stories/AssetGrid.stories.tsx, frontend/src/stories/AssetGrid.tsx, frontend/src/stories/SearchBar.tsx, frontend/src/styles/AssetBrowser.css, frontend/src/styles/Form.css, frontend/src/styles/Grid.css, frontend/src/styles/LoadingSpinner.css, frontend/src/styles/Pagination.css, frontend/src/types/cursor.ts, frontend/src/types/index.ts
This commit removes the `domain` prop from the `Imgix` component to fix an issue with the types. The `@types/react-imgix` repo doesn't yet have the new `domain` prop defined.
|#49|[PE-389-1][PE-1531] feat: add loading state to asset grid|**N/A**|
|#51|[PE-389-1][PE-1517] chore: remove the domain prop|#49|
|#52|[PE-389-1][PE-1527] feat: add search to asset browser|#51|
|#53|[PE-389-1][PE-1528] feat: catch and display imgixAPI errors|#52|
|#54|[PE-389-1][PE-1526] feat: add pagination|#53|
|#55|[PE-389-1][PE-1526-1] chore: update grid style to show more assets|#54|
=> [PE-389-1][PE-1517] chore: remove the domain prop

metadata/imgix_data/meta/system-objecttype-extensions.xml, metadata/imgix_data/services.xml, metadata/imgix_data/system-objecttype-extensions.xml
This PR creates the necessary `.xml` and `.zip` files so that users can run the 'site import' feature on SFCC to import imgix custom site settings. 
We need these settings in order to pass down an imgix API key to the page designer. These settings will likely be expanded upon in a later commit.
=> [PE-1322] feat: create metadata import files

frontend/config-overrides.js, frontend/package.json, frontend/yarn.lock
This commit uses the `mini-css-extract-plugin` to give the react app CSS bundles a predictable and unique filename. This is done so that a future build script can reference this filename when copying over the styles into the sfcc cartridge.
=> build(PE-1518): change css bundle filename

cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js
Uses @imgix/js-core to build the image src for the rendered image. Pretty self-explanatory here. Will be extended in due course to generate the srcset, etc.
=> chore: use @imgix/js-core to build image src

cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js, cartridges/int_imgix_pd/cartridge/scripts/jsCore/jsCore.js
This PR checks in a custom version of @imgix/js-core that was transpiled down to ES5, and switched out `Object.entries` for `Object.keys`. This PR should keep future PRs tidy.
For future reference, `@imgix/js-core` can be transpiled down by updating `.babelrc` in the js-core repo to be:
```json
{
"presets": ["@babel/preset-env"]
}
```
And then just run build as usual.
The Object.keys update was on line 1285.
=> chore: check in working version of @imgix/js-core

cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js, cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.json
This PR adds the imgix parameters to the sidebar according to the requirements. I'm just using basic types (strings, numbers), for now, but this can be upgraded in the future to use enums
|#76|feat: implement responsive images and set ixlib|Pending|-|
|#77|chore: write template logic to handle default params|Pending|#76|
|#82|👉 feat: add imgix parameters to component sidebar|Pending|#77|
|#79|Added apikey to defaultParams|Pending|#77|
|#83|feat: correctly set imgix parameters on rendered image|Pending|#82|
=> [fred] feat: add imgix parameters to component sidebar

frontend/src/index-sidebar.tsx
This commit removes the unused variable `buttonEl` and the handleBreakoutCancel function. The handleBreakoutCancel is automatically emited by the SFCC framework and does not need to be defined.
|#74|chore(PE-1574): add typing declaration to subscribe func|**Approved**|-|
|#75|👉 chore(PE-1574): remove unused function and variable|**Approved**|#74|
=> chore(PE-1574): remove unused function and variable

frontend/src/index-sidebar.tsx, frontend/src/types/index.ts, frontend/src/types/sfcc.ts
This commit defines the SFCC `subscribe` function types. The types were taken from the SFCC [documentation](https://documentation.b2c.commercecloud.salesforce.com/DOC4/index.jsp?topic=%2Fcom.demandware.dochelp%2Fcontent%2Fb2c_commerce%2Ftopics%2Fpage_designer%2Fb2c_host_events_custom_attr_editor.html) since the function is injected at runtime and the types cannot be inferred.
|#74|👉 chore(PE-1574): add typing declaration to subscribe func|**Approved**|-|
|#75|chore(PE-1574): remove unused function and variable|**Approved**|#74|
=> chore(PE-1574): add typing declaration to subscribe func

cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js, cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.json
I updated this since the data that needs to be stored in the component data needs to be an object, so using `image_url` as the name didn't make much sense anymore
=> chore: update imgix component data type of SF side and access

frontend/src/components/BreakoutApp.tsx, frontend/src/stories/AssetBrowser.tsx, frontend/src/stories/AssetGrid.tsx, frontend/src/stories/SearchBar.tsx, frontend/src/stories/SourceSelect.tsx, frontend/src/styles/App.css
> This PR is stacked on top of #93. It will be rebased on `next` once that stack is merged in.
This PR changes the default font for the react apps to `Roboto`.
This font is imported when the stylesheet first loads. This is not ideal, as it's not as fast as loading from a local file. However, it gets around an annoying build issue where the generated font files from `yarn build` need to be moved to the correct SFCC directory.
A later commit should probably have these files live somewhere in the cartridge.
This PR also imports the `styles/App.css` in all storybook stories, setting the default font to be Roboto. This is necessary since the components, currently, do not import `App.css` from `styles`.
=> PE-1550 feat: use roboto fontface

frontend/src/components/grids/AssetGrid.tsx, frontend/src/stories/AssetGrid.stories.tsx, frontend/src/stories/AssetGrid.tsx, frontend/src/styles/Grid.css
This PR updates the asset grid styling, bringing it up to standard with the style guide. Things that were changed included: font sizing, image sizing, column padding and margin, colours, and background colours.
=> chore: update asset grid to design guide styling

frontend/src/components/grids/AssetGrid.tsx, frontend/src/styles/Grid.css
> Stacks on top of #93. Will rebase on `next` once that stack is merged in.
An image had to be clicked for it to be selected. No styling changes reflected which image in the gallery had to be selected.
Any part of the asset, ie the filename, for example, can be clicked for it to be selected. A drop-shadow is added to the selected asset.
This commit styles the selected `AssetGrid` "card" when clicked. the `onCLick` handler was moved to the parent div to account for when a user clicks on the file name. Previously, a user had to click on the actual image for the selection to register.
The styling is applied to the "card" by conditionally adding a class to the container div. This is done by creating a component state that changes the selected `asset.id` whenever a "card" is clicked. If the …
=> PE-1584 feat: style image on select

frontend/src/components/AssetBrowser/AssetBrowser.tsx, frontend/src/components/buttons/dropdowns/SourceSelect.tsx, frontend/src/components/grids/AssetGrid.tsx, frontend/src/stories/SourceSelect.tsx, frontend/src/styles/Form.css, frontend/src/styles/Grid.css
> Stacks onto #93. Will rebase on `next` once that entire stack is merged in.
On first render, a user had to select a source before any assets were requested
The first `sources` In `sources:[]` is set as a "default" source, and its assets are requested on the first render.
This PR automatically sets the `selectedSourceId` to be `sources[0].id` on the `SourceSelect.tsx` first render. This way, the user is always greeted with a pre-selected source. It then invokes `handleSelect()` on the first render if `sources.length`, ensuring we request the automatically set "default" source's assets on the AssetGrid's first render.
Finally, the PR removes the `position: absolute` attribute from the `Form.css` file for `.ix-asset-simple-search-content`. This fixes an issue where the source select …
=> PE-1597 feat: automatically select source on first render

cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js, frontend/src/components/AssetBrowser/AssetBrowserContainer.tsx, frontend/src/index-breakout.tsx, frontend/src/services/imgixAPIService.ts, frontend/src/types/breakoutAppPublic.ts, frontend/src/types/imgixAPITypes.ts, frontend/src/types/imgixSF.ts
Before this PR rendered images had a srcset that included widths that would be too big for the image, resulting in wasted bandwidth (both for the image and the page size):
After this PR, the srcset widths are limited by the images' native resolutions:
Showing the data being passed around:
|#102|👉 feat: limit generated srcsets to image width  |Pending|-|
|#106|chore: refactor asset click handling to AssetBrowser |Pending|#102|
|#104|chore: reduce number of files in sidebar app story |**Approved**|#106|
|#105|fix: render image in sidebar app at right size |**Approved**|#104|
|#107|chore: add "add image" button to empty state |**Approved**|#105|
|#108|feat: add replace image button overlay |**Approved**|#107| …
=> feat: limit generated srcsets to image width  [f-5]

cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js, cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.json, cartridges/int_imgix_pd/cartridge/templates/default/experience/components/imgix/imageComponent.isml
Before this PR, the logic would use `#` as the empty state. I updated this to use an empty string, which is more error-safe. This PR also updates the description of the attribute.
=> chore: update linking logic

frontend/src/components/forms/search/useFocus.tsx
This commit copies 'focusRef.current' to a variable inside the `useEffect`. This fixes an issue in CI where the linter warned "The ref value 'focusRef.current' will likely have changed by the time this effect cleanup function runs."
|#129|chore: update source select dropdown, and api calls |**Approved**|#128|
|#131|chore: fix layout and styles of source select and search …
=> fix: store current focus in variable [f-7]

frontend/src/components/buttons/Button.module.scss, frontend/src/components/buttons/Button.tsx, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/forms/search/SearchBar.tsx, frontend/src/components/forms/search/useFocus.tsx
- `onClick` handler could be any function
- the submit, change, and focus handlers for the search bar were written in-line
- updating the search suggestions handled exactly the same in several places
- the search suggestion list was clickable even when it wasn't visible
- `onClick` fn is expected to be a `MouseEventHandler` for an `HTMLDivElement`.
- the submit, change, and focus handlers for the`SearchBar` are refactored into functions that can be more easily re-used inside this file. 
- The function, `updateSearchHistory` is created to handle the common task of needing to update the search suggestion list.
- The search suggestion list is hidden when the input is not focused. This prevents the suggestion list from being clickable while it's not actually visible
- chore: remove the empty …
=> chore(search): refactor handlers [f-7]

frontend/src/common/hooks/useListSelectionBehavior.tsx, frontend/src/components/buttons/Button.module.scss, frontend/src/components/buttons/Button.tsx, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/forms/search/SearchBar.tsx, frontend/src/components/forms/search/useFocus.tsx
This commit has the hook make use of its `active` prop. This prop allows us to enable/disable functionality depending on whether or not the element that uses this hook is "active". In our case, when the user is no longer navigating the dropdown the "Enter" event listener should do nothing inside this hook.
`active` prop was not being used, leaving the `Enter` keypress listener to fire unintentionally.
The `active` prop has to be truthy in order for the `Enter` event to fire.
This fixes a bug where the "Enter" keypress would always cause a source ID update, regardless of what DOM node triggered the event.
|#125|feat(search): use …
=> fix: use the active prop [f-7]

frontend/src/common/hooks/useListSelectionBehavior.tsx, frontend/src/components/buttons/Button.module.scss, frontend/src/components/buttons/Button.tsx, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/forms/search/SearchBar.tsx, frontend/src/components/forms/search/useFocus.tsx, frontend/src/components/icons/DisabledSvg.tsx
This commit adds the `clear` and `search` buttons to the search expander.
Before this PR, there was no `Clear` icon. There were also no `Search` and `Clear` buttons that appeared on search input focus.
After this PR, when a user focuses on the search field, two buttons, search and clear, appear as well below the input field.
|#129|chore: update source select dropdown, …
=> chore(search): add buttons to expander [f-7]

frontend/src/common/hooks/useListSelectionBehavior.tsx, frontend/src/components/buttons/Button.module.scss, frontend/src/components/buttons/Button.tsx, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/forms/search/SearchBar.tsx, frontend/src/components/forms/search/useFocus.tsx, frontend/src/components/icons/DisabledSvg.tsx
This commit removes the `:focus-within` styling and instead uses the `isVisible` hook to conditionally style the search bar on input focus.
|#129|chore: update source select dropdown, and api calls |**Approved**|#128|
|#131|chore: fix layout and styles of source select and search bar |**Approved**|#129|
|#132|chore: have search-bar take up container width …
=> chore(search): refactor on-focus styling [f-7]

frontend/src/common/hooks/useListSelectionBehavior.tsx, frontend/src/components/buttons/Button.module.scss, frontend/src/components/buttons/Button.tsx, frontend/src/components/buttons/dropdowns/SourceSelect.tsx, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/forms/search/SearchBar.tsx, frontend/src/components/forms/search/useFocus.tsx, frontend/src/components/icons/DisabledSvg.tsx, frontend/src/stories/Button.stories.tsx
This commit adds the `leftIcon` and `rightIcon` props and removes the `type` prop. This allows for better Icon position controls. The usage of these props has also been updated.
|#124|👉 chore: fix layout and styles of source select and search bar |**Approved**|-|
|#129|chore: update source select dropdown, and api calls |**Approved**|#128|
|#131|👉 chore: fix layout and styles of source select and search bar |**Approved**|#129|
|#132|~~chore: have …
=> chore: fix layout and styles of source select and search bar [f-7]

frontend/src/common/hooks/useListSelectionBehavior.tsx, frontend/src/components/AssetBrowser/AssetBrowser.tsx, frontend/src/components/buttons/Button.module.scss, frontend/src/components/buttons/Button.tsx, frontend/src/components/buttons/dropdowns/SourceSelect.module.scss, frontend/src/components/buttons/dropdowns/SourceSelect.tsx, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/forms/search/SearchBar.tsx, frontend/src/components/forms/search/useFocus.tsx, frontend/src/components/icons/DisabledSvg.tsx, frontend/src/services/imgixAPIService.ts, frontend/src/stories/Button.stories.tsx, frontend/src/stories/SourceSelect.stories.tsx, frontend/src/types/imgixAPITypes.ts
This PR does two things:
- it adds `type` to the sources API call to ensure we can render it in the dropdown (and moves `custom_domains` to the right place where it exists in the API data returned)
- update the source select dropdown to bring it up to design standard.
Fun extra part: I added key-based navigation to the source select dropdown as well! 
https://user-images.githubusercontent.com/615334/144582278-4b5d087a-58d1-47fb-8f77-841e30e14d78.mov
**Source with a really long name**
|#126|chore: fix className overriding …
=> chore: update source select dropdown, and api calls [f-7]

frontend/src/common/hooks/useListSelectionBehavior.tsx, frontend/src/components/AssetBrowser/AssetBrowser.module.scss, frontend/src/components/AssetBrowser/AssetBrowser.tsx, frontend/src/components/buttons/Button.module.scss, frontend/src/components/buttons/Button.tsx, frontend/src/components/buttons/dropdowns/SourceSelect.module.scss, frontend/src/components/buttons/dropdowns/SourceSelect.tsx, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/forms/search/SearchBar.tsx, frontend/src/components/forms/search/useFocus.tsx, frontend/src/components/icons/DisabledSvg.tsx, frontend/src/components/icons/SourceMenuSvg.module.scss, frontend/src/services/imgixAPIService.ts, frontend/src/stories/Button.stories.tsx, frontend/src/stories/SourceSelect.stories.tsx, frontend/src/types/imgixAPITypes.ts
This PR fixed the layout of the top bar. Before, the search bar was layed out using absolute positioning, which didn't work well with the flex box style of the container, causing the source select to take up the full width of the top bar.
|#127|👉 chore: layout top bar correctly |**Approved**|#126|
|#129|~~chore: update source select dropdown, and api calls ~~|**Merged**|#128|
|#131|~~chore: fix layout and styles of source …
=> chore: layout top bar correctly [f-7]

frontend/src/common/hooks/useListSelectionBehavior.tsx, frontend/src/components/AssetBrowser/AssetBrowser.module.scss, frontend/src/components/AssetBrowser/AssetBrowser.tsx, frontend/src/components/buttons/Button.module.scss, frontend/src/components/buttons/Button.tsx, frontend/src/components/buttons/dropdowns/SourceSelect.module.scss, frontend/src/components/buttons/dropdowns/SourceSelect.tsx, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/forms/search/SearchBar.tsx, frontend/src/components/forms/search/useFocus.tsx, frontend/src/components/icons/DisabledSvg.tsx, frontend/src/components/icons/SourceMenuSvg.module.scss, frontend/src/components/icons/SourceMenuSvg.tsx, frontend/src/services/imgixAPIService.ts, frontend/src/stories/Button.stories.tsx, frontend/src/stories/SourceSelect.stories.tsx, frontend/src/types/imgixAPITypes.ts
This PR just updates some incorrect logic to add the className in from props
|#126|👉 chore: fix className overriding |**Approved**|#125|
|#129|~~chore: update source select dropdown, and api calls ~~|**Merged**|#128|
|#131|~~chore: fix layout and styles of source select and search bar ~~|**Merged**|#129|
|#132|~~chore: have search-bar take up container width ~~|**Merged**|#131|
|#133|~~chore(search): refactor on-focus styling …
=> chore: fix className overriding [f-7]

frontend/src/components/forms/search/SearchBar.module.scss
This commit changes the button opacities from `60%` to `0.6`. This fixes an issue where when the CSS is bundled, the opacity was being set to `1%`.
=> fix(search): button opacity

frontend/src/components/buttons/dropdowns/SourceSelect.module.scss, frontend/src/components/buttons/dropdowns/SourceSelect.tsx, frontend/src/components/icons/AzureIcon.tsx, frontend/src/components/icons/GCSIcon.tsx, frontend/src/components/icons/S3Icon.tsx, frontend/src/components/icons/SearchIconSvg.tsx, frontend/src/components/icons/SourceTypeIcon.tsx, frontend/src/components/icons/WebFolderIcon.tsx, frontend/src/components/icons/WebProxyIcon.tsx
This PR creates Icon files for GCS, AWS, Azure, WebProxy, and WebFolder source types.
Source select dropdown types did not display an icon for each type of source
Source select dropdown source types display an icon for each source type
=> feat(source-select): add source type icons

frontend/src/services/imgixAPIService.ts, frontend/src/tests/services/imgixAPIService.test.ts
This commit changes the sort param to be by `-date_created`, resulting in search assets being displayed from newest to oldest.
Search results were displayed from oldest to newest.
Search results are displayed from newest to oldest. They appear in the same order as the imgix Image Manager.
=> chore(search): sort by newest

frontend/src/components/AssetBrowser/AssetBrowserContainer.tsx, frontend/src/services/imgixAPIService.ts
This commit increased the asset-grid-item count from 12 to 14. This addresses an issue where, on larger screen sizes, there were too few elements being displayed.
=> chore(search): increase page limit to fourteen

cartridges/bm_imgix_pd/cartridge/experience/editors/imgix/imgixEditorTrigger.js
This commit adds a comment that explains how the `reducer` function makes use of the `Resource.msg()` API to store "bundle" attributes in a HahsMap.
For more information on this API read here: https://documentation.b2c.commercecloud.salesforce.com/DOC4/index.jsp?topic=%2Fcom.demandware.dochelp%2FDWAPI%2Fscriptapi%2Fhtml%2Fapi%2Fclass_dw_web_Resource.html
=> chore: add comment explaining reducer func

frontend/src/components/Pagination/Pagination.module.scss, frontend/src/components/SidebarApp.module.css, frontend/src/components/Spinner/Spinner.module.scss, frontend/src/components/buttons/dropdowns/SourceSelect.module.scss, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/styles/Grid.css
This commit changes font-related `px` values to corresponding `em` values. This was asked for in the SFCC cartridge review.
Most of these `em` values assume a "base font size" of `16px`.
Some of the `em` values are not 1:1 with their previous `px` values. This was done because the 1:1 `em` value threw things off. I suspect this is because the "base font-size" for the element in question is actually different from `16px`.
> Images can be a tad misleading since they're not all the same size. You can however tell little if anything has changed.
before
after
=> PE-1789 chore: change font related px to em values

frontend/src/index-extension.tsx, frontend/src/stories/extension/products.module.scss, frontend/src/stories/extension/products.stories.tsx
This allows us to develop the extension inside storybook, rather than inside Chrome the whole time.
=> chore: copy SF HTML and CSS to Storybook for extension development

frontend/src/components/ExtensionApp.tsx, frontend/src/components/ProductPageImages.tsx, frontend/src/index-extension.tsx, frontend/src/stories/extension/ProductPage.stories.tsx, frontend/src/stories/extension/products.stories.tsx
- creates the `ExtensionApp.tsx` component. This is then used in `index-extension.tsx` to render the extension UI.
- updates `index-extension.tsx` to scrape the page for imgix custom attribute images
- passes those scraped images to the extension react app
- small typing fixes
- small storybook updates
- moves the `add image` button to come before the images
- updates the extension CSS and JS bundle
https://user-images.githubusercontent.com/16711614/149557496-f335ce62-512f-4a8e-83e3-345b00895975.mov
https://user-images.githubusercontent.com/16711614/149557645-29fc829b-2d15-4462-a575-e1b9d5ac4abf.mov
=> feat: create extension react app

cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js, test/unit/int_imgix_products_sfra/models/product/productImages.js
This PR addresses some inconsistencies in the testing and product images implementation
- Tests: hard to distinguish in testing data between SF data and imgix attribute data
- Tests: was hard to distinguish the context behind tests (whether custom attribute data was set, whether imgix base URL preference was set)
- Tests: not all edge cases were tested (e.g. requesting multiple images when no imgix base URL preference was set caused a `TypeError`)
- Product Images Model: there was a bug where requesting multiple images when no imgix base URL preference was set would cause `TypeError`
- Product Images Model: the organisation made it difficult to reason about the mode of operation, when there were distinctly three modes of operation: using custom attribute data, using SF data w/ imgix base …
=> chore: refactor product images tests and model implementation to be more logical and fix some bugs"

frontend/src/components/AssetBrowser/AssetBrowser.module.scss
This commit adds a `min-height` of `730px` to the `.assetBrowser` class. This fixes an issue where the container would not take up the entire height of the modal.
This will mean that on smaller windows/devices the frame will be scrollable.
Part of the problem is a script SFCC runs in the background that listens for window and or frame resizing. It impedes us from "reactively" sizing the container as the iframe w/h can be changed at any time by the SFCC background script. Moreover, trying to get the `document.offsetHeight` or similar techniques for getting the window size have proven unreliable. Probably at least in part due to that background SFCC script.
https://user-images.githubusercontent.com/16711614/150380148-f52826e6-9b0a-4dae-a83f-65cd6345b952.mov
"mobile"/smaller screens …
=> fix: add min-height to asset container

cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js, test/unit/int_imgix_products_sfra/models/product/productImages.js
This PR implements a part of the Salesforce required feedback to allow the product image proxying to be disabled. When the custom preference is set to "false" or "disabled", then the integration will fall back to passing through the images stored in SF, without modification.
=> feat: disable proxying product images when custom preference is disabled

cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js, test/unit/int_imgix_products_sfra/models/product/productImages.js
- The SF images images were being iterated over, and only the URL was being replaced by the custom attribute data. This could (and probably would) have led to scenarios where the data was incorrect/out-of-sync. For example, if there were more or less SF images than custom attribute images, some images could have no url set (in the case of there being more SF images), or the image would not be displayed (if SF had less images). Furthermore, if the order of the images was different, the title and alt would associated with the wrong image.
- `sourceWidth` was being added to the imgix URL, which is incorrect
- The code iterates solely over the custom attribute images, ensuring that it can no longer be out of sync
- `sourceWidth` is no longer added to the imgix URL
- The code has been …
=> chore: simplify product images custom attribute implementation

cartridges/bm_imgix_pd/cartridge/experience/editors/imgix/imgixEditorTrigger.js, cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js, frontend/src/components/SidebarApp.module.scss, frontend/src/components/SidebarApp.tsx, frontend/src/index-sidebar.tsx
This PR makes it so that settings the `imgixEnablePageDesigner` to `No`, or `false`, will keep the imgix PD component and ISML templates from rendering on the page.
This PR also changes the `SidebarApp` CSS module to be a SASS module.
Markup when disabled
Sidebar when disabled
=> feat!: add preference to disable page designer

.gitignore, package.json, src/cartridges/SFTypes.ts, src/cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.ts, src/cartridges/tsconfig.json, yarn.lock
This PR is born out of frustration of writing plain JS without type checking, causing potentially future problems in the development of the product images model (and other SF JS). This is not fixed in stone, and am willing to revert this if there is a significant pushback.
=> chore: migrate product images modal to typescript

cartridges/SFTypes.js, cartridges/commonTypes.js, cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js, src/cartridges/commonTypes.ts, src/cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.ts, test/unit/int_imgix_products_sfra/models/product/productImages.js
This PR updates the product images model and corresponding tests to use the new schema agreed for the imgix products custom attribute.
Also the idea here is that we can share the `commonTypes` file between the cartridges and the frontend projects to ensure type safety. I'm not quite sure how to do this yet, my best idea so far is with a simple `cp`
=> chore: use new custom attribute schema

package.json
This PR aims to fix the build script that's breaking on CI. `pushd` cannot be used on our circleCI instance.
=> fix: update cartridge build script so it doesn't break on ci

frontend/src/components/card/AssetCard.tsx, frontend/src/components/grids/AssetGrid.tsx, frontend/src/stories/Card.stories.tsx, frontend/src/stories/styles/Grid.stories.tsx
Each card was hardcoded onto the `AssetGrid.tsx` component.
The component uses the `AssetCard.tsx` component for each card.
- before
- after
=> refactor(asset-grid): use asset-card

frontend/src/components/ProductImage/ProductImageContainer.module.scss, frontend/src/components/ProductImage/ProductImageContainer.tsx, frontend/src/components/ProductPageImages.module.scss, frontend/src/components/ProductPageImages.tsx, frontend/src/components/card/AssetCard.tsx, frontend/src/components/grids/AssetGrid.tsx, frontend/src/index-extension.tsx, frontend/src/stories/Card.stories.tsx, frontend/src/stories/extension/ProductImageContainer.stories.tsx, frontend/src/stories/extension/products.stories.tsx, frontend/src/stories/styles/Grid.stories.tsx
The extension app did not use `AssetCard.tsx` or `FrameButton.tsx` components.
`frontend/src/components/ProductImage/ProductImageContainer.tsx` extension component uses these components.
=> refactor(products): use asset-card & frame-button

frontend/src/components/ExtensionApp.tsx, frontend/src/components/ProductImage/ProductImageContainer.module.scss, frontend/src/components/ProductImage/ProductImageContainer.tsx, frontend/src/components/ProductPageImages.module.scss, frontend/src/components/ProductPageImages.tsx, frontend/src/components/card/AssetCard.tsx, frontend/src/components/grids/AssetGrid.tsx, frontend/src/components/image/AssetCardImage.tsx, frontend/src/index-extension.tsx, frontend/src/stories/Card.stories.tsx, frontend/src/stories/extension/ProductImageContainer.stories.tsx, frontend/src/stories/extension/products.stories.tsx, frontend/src/stories/styles/Grid.stories.tsx
- `ExtensionApp.tsx`, `AssetCard.tsx`, & `AssetCardImage.tsx` could not use 
- `IImgixMetadata`
- `IImgixCustomAttributeImage`
- `IImgixCustomAttributeSwatch`, or 
- `IImgixCustomAttribute` types.
The component prop type definitions include these new types.
=> chore: use new types in extension and asset-card

src/extension/manifest.json, src/extension/options.html, src/extension/options.js
This commit creates the extension's `options.js/html` files where the imgix API key will be set/read. The extension settings can be set from the `chrome://extensions` settings page. It will not open in a new tab but, instead, it will open in a pop-up.
The extension settings are saved to the `browser.storage` local storage.
The `options.js` file validates the imgix API key input on save and restore. If the key is invalid or errors out for any other reason, the value in `browser.storage` will not be updated.
=> feat: create extension settings page

frontend/src/components/ExtensionApp.tsx, frontend/src/components/layouts/Modal.tsx, frontend/src/index-extension.tsx
This PR has the `ExtensionApp` component accept an `apiKey` string prop. It then passes that prop onto the `AssetBrowserContainer` component inside a `Modal` component. The modal only opens once the user has clicked on one of the buttons inside the `ProductImageContainer`.
[modal-open-on-click.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/vkhjmXjzdqOiU0HS7RdK/0d94ec17-f2ec-47aa-9b1f-ce1901857683/modal-open-on-click.mov)
=> feat(extension): open im-modal on click

frontend/src/components/ExtensionApp.tsx
This PR refactors the duplicate checking logic to happen earlier in the flow, then the image-selected logic is being invoked, rather than the when the save logic is being invoked. This prevents saving a duplicate for both when there is and there isn't selected-image data.
It was possible to add a duplicate image when just "adding" and not "replacing"
It's no longer possible to add duplicate.
=> fix: prevent adding duplicate when replacing image

frontend/src/components/ExtensionApp.tsx, frontend/src/components/buttons/FrameButton/FrameButton.module.scss, frontend/src/components/buttons/dropdowns/SourceSelect.module.scss, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/layouts/Modal.module.scss, frontend/src/components/layouts/Portal.tsx, frontend/src/stories/extension/products.module.scss, frontend/src/stories/extension/products.stories.tsx
This PR overrides SFCC `box-sizing: content-box` to be `border-box`. This is necessary at the component level because they have several css-resets that counteract our App-scoped stylesheets.
[box-sizing-before.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/vkhjmXjzdqOiU0HS7RdK/76d43741-984c-48a6-b829-cc69d4f427bf/box-sizing-before.mov)
[box-sizing-after.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/vkhjmXjzdqOiU0HS7RdK/d98ba5e1-6e0b-47c5-8120-5f6f07c64580/box-sizing-after.mov)
=> fix: enforce border-box for box-sizing

frontend/src/components/ActionBar/ActionBar.module.scss, frontend/src/components/ActionBar/ActionBar.tsx, frontend/src/components/ExtensionApp.module.scss, frontend/src/components/ExtensionApp.tsx, frontend/src/components/ProductImage/ProductImageContainer.module.scss, frontend/src/components/ProductImage/ProductImageContainer.tsx, frontend/src/components/ProductPageImages.module.scss, frontend/src/components/buttons/FrameButton/FrameButton.module.scss, frontend/src/components/buttons/dropdowns/SourceSelect.module.scss, frontend/src/components/card/AssetCard.module.scss, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/layouts/Modal.module.scss, frontend/src/components/layouts/Portal.tsx, frontend/src/index-extension.tsx, frontend/src/stories/extension/products.module.scss, frontend/src/stories/extension/products.stories.tsx
When replacing an image, it was possible to select a duplicate or images already associated with the product.
When selecting an image, you cannot select a duplicate of the current or another image already associated with the product.
=> fix: ensure duplicated products images can't be added

frontend/src/components/ActionBar/ActionBar.module.scss, frontend/src/components/ActionBar/ActionBar.tsx, frontend/src/components/ExtensionApp.module.scss, frontend/src/components/ExtensionApp.tsx, frontend/src/components/ProductImage/ProductImageContainer.module.scss, frontend/src/components/ProductImage/ProductImageContainer.tsx, frontend/src/components/ProductPageImages.module.scss, frontend/src/components/buttons/FrameButton/FrameButton.module.scss, frontend/src/components/buttons/dropdowns/SourceSelect.module.scss, frontend/src/components/card/AssetCard.module.scss, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/layouts/Modal.module.scss, frontend/src/components/layouts/Portal.tsx, frontend/src/index-extension.tsx, frontend/src/stories/extension/products.module.scss, frontend/src/stories/extension/products.stories.tsx
The product images container would not update even after a selection was made and the JSON field was updated.
The products images container updates to show the newly selected image, accurately reflecting the state of the JSON.
[update-p-image-container-on-save.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/vkhjmXjzdqOiU0HS7RdK/95180563-3033-4034-89d2-e88b7739cdcf/update-p-image-container-on-save.mov)
=> feat: track product images in state

frontend/src/components/ActionBar/ActionBar.module.scss, frontend/src/components/ActionBar/ActionBar.tsx, frontend/src/components/ExtensionApp.module.scss, frontend/src/components/ExtensionApp.tsx, frontend/src/components/ProductImage/ProductImageContainer.module.scss, frontend/src/components/ProductImage/ProductImageContainer.tsx, frontend/src/components/ProductPageImages.module.scss, frontend/src/components/ProductPageImages.tsx, frontend/src/components/buttons/FrameButton/FrameButton.module.scss, frontend/src/components/buttons/dropdowns/SourceSelect.module.scss, frontend/src/components/card/AssetCard.module.scss, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/layouts/Modal.module.scss, frontend/src/components/layouts/Portal.tsx, frontend/src/index-extension.tsx, frontend/src/stories/extension/products.module.scss, frontend/src/stories/extension/products.stories.tsx
This PR updates the type definitions and implementations of `openBreakoutOnClick` and `ProductPageImage` `onClick` to allow for the `id` optional argument.
=> feat: send selected id on click if it exists

frontend/src/components/ActionBar/ActionBar.module.scss, frontend/src/components/ActionBar/ActionBar.tsx, frontend/src/components/AssetBrowser/AssetBrowser.tsx, frontend/src/components/ExtensionApp.module.scss, frontend/src/components/ExtensionApp.tsx, frontend/src/components/ProductImage/ProductImageContainer.module.scss, frontend/src/components/ProductImage/ProductImageContainer.tsx, frontend/src/components/ProductPageImages.module.scss, frontend/src/components/ProductPageImages.tsx, frontend/src/components/buttons/FrameButton/FrameButton.module.scss, frontend/src/components/buttons/dropdowns/SourceSelect.module.scss, frontend/src/components/card/AssetCard.module.scss, frontend/src/components/card/AssetCard.tsx, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/image/AssetCardImage.tsx, frontend/src/components/layouts/Modal.module.scss, frontend/src/components/layouts/Portal.tsx, frontend/src/index-extension.tsx, frontend/src/stories/extension/ProductImageContainer.stories.tsx, frontend/src/stories/extension/products.module.scss, frontend/src/stories/extension/products.stories.tsx, frontend/src/types/breakoutAppPublic.ts, frontend/src/types/index.ts, frontend/src/types/productImage.ts, src/cartridges/commonTypes.ts
This PR removes the `IProductImageData` type, since it's a duplicate of the `IImgixCustomAttribute` type. It also removes references to `swatches` and `size_type` since those are out of scope for this MVP.
=> chore: remove swatches and views from types

frontend/src/components/ActionBar/ActionBar.module.scss, frontend/src/components/ActionBar/ActionBar.tsx, frontend/src/components/AssetBrowser/AssetBrowser.tsx, frontend/src/components/ExtensionApp.module.scss, frontend/src/components/ExtensionApp.tsx, frontend/src/components/ProductImage/ProductImageContainer.module.scss, frontend/src/components/ProductImage/ProductImageContainer.tsx, frontend/src/components/ProductPageImages.module.scss, frontend/src/components/ProductPageImages.tsx, frontend/src/components/buttons/FrameButton/FrameButton.module.scss, frontend/src/components/buttons/dropdowns/SourceSelect.module.scss, frontend/src/components/card/AssetCard.module.scss, frontend/src/components/card/AssetCard.tsx, frontend/src/components/forms/search/SearchBar.module.scss, frontend/src/components/image/AssetCardImage.tsx, frontend/src/components/layouts/Modal.module.scss, frontend/src/components/layouts/Portal.module.scss, frontend/src/components/layouts/Portal.tsx, frontend/src/index-extension.tsx, frontend/src/stories/extension/ProductImageContainer.stories.tsx, frontend/src/stories/extension/products.module.scss, frontend/src/stories/extension/products.stories.tsx, frontend/src/types/breakoutAppPublic.ts, frontend/src/types/index.ts, frontend/src/types/productImage.ts, src/cartridges/commonTypes.ts
This commit adjusts the `Portal` and `Modal` component styles to ensure the `AsseetBrowserContainer` modal fits inside of the sfcc page.
[modal-before.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/vkhjmXjzdqOiU0HS7RdK/3b08423e-2ed1-48ab-ad64-7d0a8bf7699b/modal-before.mov)
[modal-after.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/vkhjmXjzdqOiU0HS7RdK/f4af37e2-16e4-4f01-9431-8aa4660eee17/modal-after.mov)
=> chore(extension): ensure modal fits on page

src/cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.ts, test/unit/int_imgix_products_sfra/models/product/productImages.js
Before this PR, if the imgix custom attribute in the products data was an empty array (and not just simply an empty string), the model would not return any images. Now the model will fallback to the SF images if no custom attribute images exist.
=> fix: fallback to SF images when custom attribute array is empty

frontend/src/index-extension.tsx, src/extension/manifest.json
This PR updates the Browser extension to work with Chrome manifest v3. This is required to submit to the Chrome Web Store. I ran through a whole workflow (setting API key -> adding image to product -> checking image renders on PDP) but I recommend that this be tested by a third party as well. (Be sure to `yarn deploy:extension` before testing!)
NB: host_permissions is not needed since in v3 content_scripts are automatically added to host_permissions
=> chore(extension): update to manifest v3

frontend/src/components/ExtensionApp.module.scss, frontend/src/components/ExtensionApp.tsx, frontend/src/components/ProductImage/ProductImageContainer.module.scss, frontend/src/components/ProductImage/ProductImageContainer.tsx, frontend/src/components/ProductPageImages.module.scss, frontend/src/components/ProductPageImages.tsx, frontend/src/tests/extensionApp/extension_App.test.tsx
- There was no delete button
- The replace button did not match the comps
- the box-sizing was getting overridden by sfcc
- delete buttons added
- replace button matches comps
- box-sizing no longer gets overridden
[delete-replace-video.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/vkhjmXjzdqOiU0HS7RdK/0cdb2930-0cb2-4e5d-be9d-bab43d32d149/delete-replace-video.mov)
=> feat: add delete button to proudct images

frontend/src/components/ProductImage/ProductImageContainer.tsx
Before this commit, it was possible for the asset-card hover styles to
still be visible even after the modal was opened.
=> fix: ensure hover goes away on modal open

frontend/src/index-extension.tsx
Storybook and tests did not have access to a testing API key in the extension.
A testing API key is automatically inserted into the extension
In order for this to work, there needs to be a `.env` file inside `/src` to read the `IMGIX_API_KEY` from.
=> test: feed dev api key on local builds

frontend/src/components/buttons/SourceSelectButton.tsx
This commit adds a label-specific data-testid to the source-select
button. This was done this way to ensure we could wait for the selected
source label to populate inside of the tests.
=> test: add data-testid to source-select button

frontend/src/stories/extension/products.stories.tsx, frontend/src/tests/extensionApp/extension_App.test.tsx
This PR adds tests that ensure, whenever an image is being replaced, it's source is automatically set in the source dropdown.
This PR also updates the test custom attribute JSON to match the expected values from the source more closely.
=> test: source automcatiicaly requested on render

frontend/src/components/ActionBar/ActionBar.module.scss, frontend/src/components/ExtensionApp.tsx, frontend/src/components/ProductImage/ProductImageContainer.module.scss, frontend/src/components/ProductImage/ProductImageContainer.tsx, frontend/src/components/ProductPageImages.tsx, frontend/src/components/forms/attributes/AttributeForm.module.scss, frontend/src/components/forms/attributes/AttributeForm.tsx, frontend/src/components/forms/attributes/AttributeFormContainer.tsx, frontend/src/components/icons/ButtonListSvg.tsx, frontend/src/components/layouts/Modal.module.scss
This PR creates the `AttributeForm` component that opens as a modal inside the extension. This component allows you to set/update the `alt` and `title` attributes of a selected image.
This PR also creates the `ButtonList` icon.
This PR also includes some small styling adjustments to account for the `rem` value for SFCC bot being `16px`.
[alt-title-settings.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/vkhjmXjzdqOiU0HS7RdK/50754f26-b91f-4949-8117-8ba9610c2899/alt-title-settings.mov)
=> feat: create attribute-form component

frontend/src/components/buttons/FrameButton/FrameButton.tsx, frontend/src/components/forms/search/SearchBar.tsx
Could not press enter to search for images
- FrameButton now accepts a `type` prop that allows it to set its behavior to 'button | reset | submit'.
- You can now press 'enter' to search
[search-on-enter.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/vkhjmXjzdqOiU0HS7RdK/e5dcf8dc-a486-44f8-a106-c361ba89a080/search-on-enter.mov)
=> feat: search on enter keypress

src/cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.ts, src/cartridges/int_imgix_products_sfra/cartridge/scripts/imgix/imgix.ts, test/unit/int_imgix_products_sfra/models/product/productImages.js
This PR implements the following:
- auto-sizing according to the default SF data (800x800 for large images, 400x400 for medium, and 140x140 for small)
- uses @imgix/js-core to create all URLs
- sets ixlib properly
This PR also refactored the tests to better support this new functionality
=> feat: implement auto-sizing, add js-core, and set ixlib

frontend/src/components/SidebarApp.module.scss, frontend/src/components/SidebarApp.tsx
Before this commit the sidebar image was not filling it's container,
leaving a small gap between the image and the right hand side.
=> fix: make sidebar img fill container width

frontend/src/components/SidebarApp.module.scss
This commit ensures the button icon SVG is set to white. Before this
commit, the button icon was set to the incorrect color.
=> fix: replace button icon color

cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.json
This commit fixes a couple of typos in the help-text shown on hover in the Page Designer.
=> chore: fix help-text typos

frontend/src/components/forms/search/SearchBar.tsx
Before this commit, serach term in the serach bar would not update to
reflect the selected term from the history.
After this commit, the search term in the search bar updates to the
selected item.
https://user-images.githubusercontent.com/16711614/155264340-571e07dd-7682-4f83-a8e8-4c4507e01b34.mov
=> fix: set search-term on search-history click

frontend/src/components/ExtensionApp.module.scss, frontend/src/components/ExtensionApp.tsx, frontend/src/index-extension.tsx, frontend/src/stories/extension/products.stories.tsx
The extension app was being added to a table within a table within the product attributes table. This made it so that the other table/table rows on the page would expand to whatever size our product images table became.
A new table is added to the page outside of the product attributes table. This ensures layout is not affected as we add more and more images.
Since what's being submitted is only the custom attribute JSON, this change does not affect our ability to save the changes to the custom attribute.
https://user-images.githubusercontent.com/16711614/155224299-99de8ad1-73c9-44e0-8033-ae5e63da4747.mov
=> fix: ensure extension app doesnt affect layout

frontend/src/components/AssetBrowser/AssetBrowser.module.scss, frontend/src/components/ProductImage/ProductImageContainer.module.scss, frontend/src/components/ProductPageImages.module.scss, frontend/src/components/card/AssetCard.module.scss, frontend/src/components/card/AssetCard.tsx, frontend/src/components/grids/AssetGrid.module.scss, frontend/src/components/image/AssetCardImage.tsx, frontend/src/services/imgixAPIService.ts, frontend/src/styles/Grid.css
- The grid item would scretch to fill the available space
- Only 14 items were displayed at a time
- grid items have a fixed 1:1 aspect ratio
- 20 items are displayed at a time
[grid-before.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/vkhjmXjzdqOiU0HS7RdK/eaf20676-43c0-4539-9e43-1e4a44f1dd89/grid-before.mov)
https://user-images.githubusercontent.com/16711614/155194563-bd7eda79-96b6-4973-b1e2-92408d5de4f0.mov
=> chore: display grid items with fixed ar

cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js
If the `defaultParams` custom config for page designer was left empty, no images would render in the page designer.
If the `defaultParams` are null they are set to an empty string, ensuring rendering doesn't break.
=> fix: ensure default-params never null

frontend/src/components/SidebarApp.module.scss
Before this commit, when no image was selected, the placeholder wouldn't
span the width of the container. After this commit, with or without an
image in the container, the placeholder background spans the width of
the container.
=> fix(sidebar): set fixed width for image container

frontend/src/components/ExtensionApp.tsx, frontend/src/components/ProductImage/ProductImageContainer.tsx, frontend/src/components/ProductPageImages.tsx
This commit disabled the extension buttons if the product is `locked` on
SFCC. This ensures that the extension cannot be interacted with while
the product is locked.
It does this by storing a boolean tracking if the "Locked" label currently
reads as "Locked" or not.
This commit adds a `disabled` prop to the ProductImageContainer and
ProductPageImages components in order to achieve this.
https://user-images.githubusercontent.com/16711614/155265722-7815924a-70e9-47ea-9ad2-64c9586b5ddf.mov
=> feat: disable extension if product is locked

cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js
Before this PR, the `srcset` had an incorrect ixlib. Now, the srcset is set correctly.
=> fix(pd): set ixlib correctly for srcset

cartridges/int_imgix_pd/cartridge/experience/components/imgix/imageComponent.js, cartridges/int_imgix_pd/cartridge/templates/default/experience/components/imgix/imageComponent.isml
Before this PR, in the Page Designer, the img tag's `sizes` attribute could be set to `undefined` or `null` depending on the situation. After this PR, two precautions were taken to ensure this can't happen.
1. The `model.image_sizes` data that is passed to the ISML template is only set if `content.sizes` actually has a useful value (i.e. not null-y and not an empty string)
2. In the ISML template, if no value is passed, before this would set `sizes` to `null`. Now, sizes is set to an empty string, which instructs browsers to fallback to the default value (`100vw`). I chose not to set `100vw` as the default since this allows browsers to behave smarter as they are more developed.
=> fix: ensure sizes is never set to null/undefined

README.md
imgix docs can't resolves GH relative URLs. We need to make this an absolute URL for the docs page to read the link correctly.
=> docs: make user guide link an absolute URL

frontend/package.json, frontend/src/index.tsx, frontend/src/services/imgixAPIService.ts, frontend/yarn.lock
This PR adds the `x-imgix-plugin` header to requests made to the imgix management API, made possible by the imgix-management-js library.
Outstanding questions:
- what should the `x-imgix-plugin` be set to? At the moment, it's set to `sfcc/v<VERSION>`
- should we have different `x-imgix-plugin` values for different sections of the plugin?
🛑 This is currently blocked by the imgix API not allowing the `x-imgix-plugin` header in the CORS OPTIONS request, but with CORS turned off the request worked.
=> chore: add tracking header to imgix API requests

cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.js, src/cartridges/int_imgix_products_sfra/cartridge/models/product/productImages.ts, src/extension/manifest.json
- only domains with the `salesforce.com` [glob](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#matchAndGlob) pattern would load the extension.
- management-js ixlib version did not match extension version
- domains with the `demandware.com` [glob](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#matchAndGlob) pattern will also load the extension.
- management js version matches extension version
1. clone branch this locally
2. install unpacked extension in chrome
3. enter the API key in extensions settings
4. try to us in a `*.demandware.com/*ViewProduct_52*` domain
=> fix: include demandware in extension glob
